axkr/symja_android_library

symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/AbstractRubiTestCase.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RubiIssue72.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RubiTests001.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RubiTests002.java
This PR adds a unit test for the issue #72 that includes about 200 small test cases for Rubi's internal utility-functions. The test cases were automatically extracted from the `Trace` when integrating this problem in Mathematica. Therefore, when we find the reasons why some of the tests fail, chances are good that we can understand why this integral is solved incorrectly by SymJa.
I have adapted the `AbstractRubiTestCase` to make it accept Mathematica syntax, which helps when creating this kind of test code completely automatically from within Mathematica.
=> Test for issue 72, add option for Mathematica syntax in Rubi tests

symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/AbstractRubiTestCase.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RuleTestAlgebraicFunctions.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RuleTestExponentials.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RuleTestHyperbolicFunctions.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RuleTestIndependentTestSuites.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RuleTestInverseHyperbolicFunctions.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RuleTestInverseTrigFunctions.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RuleTestLogarithms.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RuleTestSpecialFunctions.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/RuleTestTrigFunctions.java
This PR adds one test class for each subsection of the Rubi test suite.
It is meant to check that the integration rule used by SymJa is the same as the one used by Mathematica Rubi.
=> Add test-cases that check if the correct Rubi rule was used by SymJa

symja_android_library/matheclipse-core/pom.xml, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/Algebra.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/convert/rings/SymjaRings.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/convert/rings/SymjaRingsTest.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/system/LowercaseTestCase.java, symja_android_library/pom.xml
This PR adds more rigorous support for polynomial factorization, polynomial GCD, polynomial extended GCD using [Rings library](https://github.com/PoslavskySV/rings). It adds conversion from `IExpr` to elements of fields of rational functions over different coefficient rings. For now, available coefficient rings include rational numbers (Q), modular integers (Zp), and field extensions (Q(alpha...)).
All methods are placed in `org.matheclipse.core.convert.rings.SymjaRings`. E.g. polynomial factorization:
```java
IExpr expr = ...;
// if squareFree == true, only square free factorization will be produced
// this is equivalent to plain MMA's Factor[expr] or FactorSquareFree[expr]
IExpr factors = FactorOverQ(expr, squareFree);
// factorize modulo number
java.math.BigInteger modulus = ...;
IExpr …
```
=> Added compatability methods with Rings library

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/Console.java
Since the documentation is always for the most current version, you should probably use it here. You might want to update the three examples as well unless they are working fine.
=> Use most recent MathCell

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/Console.java
Version 1.2.0 was a bit of a release mistake, since it's really from a couple months ago and I can't purge the CDN. The current documentation matches 1.2.1 and has a better Gauss hypergeometric function.
=> Use latest version of Math

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/output/JavaComplexFormFactory.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/output/JavaDoubleFormFactory.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/output/JavaScriptFormFactory.java
Fixes a misplaced paren that breaks the expression:
* Before: `(x+y)^-1` => `(1/x+y)`
* After: `(x+y)^-1` => `1/(x+y)`
=> Fix output forms of Reciprocals for compound expressions: 1/(x+y)

symja_android_library/pom.xml
This PR fixes the scope of the Junit dependencies to `test`. This was forgotten accidentally and caused Symja to have a runtime and compile dependency to junit.
=> Fix scope of Junit dependencies to "test"

symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/archunit/ArchUnitTests.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/archunit/CodingRulesTest.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/archunit/CyclicDependencyRulesTest.java
With this PR I suggest to use the JUnit integration of ArchUnit better. This reduces boiler-plate code and decreses the runtime significantly (more than the factor two with respect to all tests in the package).
For this the test-methods in `ArchUnitTests` now only static fields annotated with @ArchTest and @AnalyzeClasses to
define all rules, like it is described in https://www.archunit.org/userguide/html/000_Index.html#_junit_support.
Because different test used different scope of packages, the class uses the widest scope and analysis all `org` packages.
Furthermore I disabled failing tests instead of commenting them out. This way it is ensured that the tests always compile, because they are kept in sync with the code base when some API evolves.
=> Improve and speed up ArchUnit tests

symja_android_library/matheclipse-io/pom.xml, symja_android_library/pom.xml
The dependency `com.tngtech.archunit:archunit-junit4` has a transitive dependency to `com.tngtech.archunit:archunit`, so there is no need to specify the latter explicitly.
=> Remove redundant ArchUnit test dependencies

symja_android_library/eclipse/toggle-snapshot-version-locking.launch
As discussed this PR adds a Eclipse launch-configuration for a Maven build that toggles locking of snapshot-dependencies versions.
When a dependency uses a not locked snapshot-version, it is locked to the latest version available (querying the dependency repositories for new snapshots in each run).
When a already locked dependency version is encountered, it is unlocked (i.e. the ordinary `-SNAPSHOT` version suffix is appended to the 'main' version).
In order to update locked versions to the latest snapshots, just run the build twice.
It is a bit unpleasant at the moment that the hipparchus snapshot-dependencies are not locked, while the apfloat dependency is locked. Therefore manual adjustment is probably required after the toggle-snapshot-locking build had run.
With this launch-config, I …
=> [Build] add Eclipse Maven launch-config to toggle snapshot locking

symja_android_library/eclipse/symja--build.launch, symja_android_library/eclipse/symja--clean.launch
As requested in PR #245 this PR adds two Maven-build launch configurations for the Eclipse IDE.
One for launch a Maven build that performs all phases up to `verify`. After the verify phase only the phases `install` (which installs the build artifacts into the local Maven repository) and `deploy` are left.
While the `deploy` phase is not possible because the corresponding configuration and setup is missing, the `install` phase is usually not necessary, unless you want to consume the build artifacts locally for another Maven build.
Therefore to build a project locally to see if the build is successful and to inspect the build artifacts, I usually use the verify phase.
Please let me know if you prefer another target phase.
Additionally I added one launch-configuration to start a clean build …
=> [Build] add Eclipse launch-configs for verify and clean Maven builds

symja_android_library/matheclipse-api/pom.xml, symja_android_library/matheclipse-beakerx/pom.xml, symja_android_library/matheclipse-core/pom.xml, symja_android_library/matheclipse-external/pom.xml, symja_android_library/matheclipse-io/pom.xml, symja_android_library/pom.xml
With this PR I suggest to clean up the dependencies to keep the set of dependencies of each module (especially matheclipse-core) minimal, to not pull unnecessary dependencies.
Furthermore declared transitive compile-dependencies are removed, since they are pulled in automatically. Therefore declaring them is just additional text.
To get an overview about all available dependencies one can for example use the `Dependency-Hierarchy` tab in Eclipse's Pom-Editor.
In detail:
- Move `org.commonmark` dependencies from matheclipse-core to matheclipse-api and matheclipse-io 
- Move `commons-codec` from matheclipse-core to matheclipse-api
- Move `jackson-datatype-jsr310` from matheclipse-external to matheclipse-io
- Remove transitive dependencies of the following dependencies
+ guava
- …
=> Clean up Maven dependencies

symja_android_library/matheclipse-jar/pom.xml
This reverts commit 639ae843b680fe8223fa1bad893510e8bbc2eb21.
=> Revert "#253 set docker image to openjdk:11-slim-buster"

symja_android_library/matheclipse-api/pom.xml, symja_android_library/matheclipse-beakerx/src/main/java/com/twosigma/beakerx/symjamma/evaluator/SymjaMMAWorkerThread.java, symja_android_library/matheclipse-beakerx/src/main/java/com/twosigma/beakerx/symjamma/widgets/Interactive.java, symja_android_library/matheclipse-core/pom.xml, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/numbertheory/SortedMultiset_BottomUp.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/numbertheory/SortedMultiset_TopDown.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/polynomials/longexponent/ExprTermOrderByName.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/polynomials/symbolicexponent/SymbolicTermOrderByName.java, symja_android_library/matheclipse-external/pom.xml, symja_android_library/matheclipse-gpl/pom.xml, symja_android_library/matheclipse-io/pom.xml, symja_android_library/pom.xml
As discussed in #254 this PR unifies the Logger-APIs used in Symja to be only log4j-2-api and removes transitively visible dependencies from non-application Symja modules to the log4j-core logging framework implementation.
Furthermore log4j-core is now used for tests in (is a test-dependencies of) core instead of slf4j-simple.
=> [Logging] use only log4j-2 Loggers and only depend on api (#254)

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/Algebra.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/core/rubi/AbstractRubiTestCase.java
I think the `Algebra.Debug` Flag is not relevant and can be removed. It is only used in AbstractRubiTestCase. My impression is that it is unrelated.
=> [CleanUp] Remove irrelevant Algebra.DEBUG flag

symja_android_library/matheclipse-beakerx/src/main/java/com/twosigma/beakerx/symjamma/evaluator/SymjaMMAWorkerThread.java, symja_android_library/matheclipse-beakerx/src/main/java/com/twosigma/beakerx/symjamma/widgets/Interactive.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/FileFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/IOFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/PatternMatching.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/StructureFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/EvalControlledCallable.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/EvalEngine.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/util/MagicProcessor.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/F.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/numbertheory/SortedMultiset_BottomUp.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/numbertheory/SortedMultiset_TopDown.java, symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/servlet/AJAXQueryServlet.java, symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/servlet/MMAAJAXQueryServlet.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/archunit/CodingRulesTest.java
- This PR unifies and simplifies how Loggers are obtained (using `LogManager.getLogger();`, which is caller sensitive and makes passing the class obsolete) and unifies the Logger names to the Java convention for static final fields.
- Checks for the right `Logger` class in the `CodingRulesTest`
- Changes `EvalEngine.getOut/ErrPrintStream()` to return `System.out/err` in case the corresponding stream is null.
This way null is never returned. This is mainly for convenience because all callers within Symja behaved like that. Only when the EvalEngine was copied on exit null was useful as return value. Therefore I added a new method `EvalEngine.setPrintStreamsOf()` that copies the references from another EvalEngine. The System.out/err stream should not be copied here, because they can change …
=> PrintStream handling and Logger improvements

symja_android_library/matheclipse-api/src/test/java/org/matheclipse/api/TestPods.java, symja_android_library/matheclipse-api/src/test/java/org/matheclipse/api/TestPodsStrict.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/Algebra.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/BooleanFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/ManipulateFunction.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/OutputFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/PatternMatching.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/Programming.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/StructureFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/WL.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/polynomials/PolynomialHomogenization.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/polynomials/PolynomialHomogenizationNew.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/eval/MMAConsoleTestSingleRun.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/others/HomogenizationJUnit.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/LowercaseTestCase.java
Access static members through the class instead via an object of that class to fix corresponding warnings.
Or is it important that an EvalEngine is created in the cases where for example `EvalEngine.get().resetModuleCounter4JUnit();` was called like in `TestPods`?
=> [CleanUp] access static members through class and not through objects

symja_android_library/log4j2.properties, symja_android_library/matheclipse-api/pom.xml, symja_android_library/matheclipse-io/pom.xml, symja_android_library/pom.xml
As already mentioned in PR #254 the log4j-core implementation does not consider the log4j2.properties configuration file located in the root Symja module, because that file is not on the classpath of those sub-modules.
This PR ensures that the log4j2.properties configuration file is included into those Symja modules that depend on the log4j-core implementation (and therefore have it on their classpath), so it is picked-up by log4j-core.
This is an important prerequisite to resolve #272.
Furthermore improve and clean up the log4j2.properties file:
+ Print message with level `error` and above to `System.err` and all messages with level `warn` or below to `System.out`
- remove commented out line
- remove unused logger named rolling (would only be used by a class in package …
=> [Logging] make log4j2-config available to log4j-core and improve it

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/IOFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/IntegerFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/JavaFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/LinearAlgebra.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/ManipulateFunction.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/NumberTheory.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/StatisticsFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/StringFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/Solve.java, symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/builtin/SwingFunctions.java
The method `IOFunctions.printMessage(ISymbol, Exception, EvalEngine)` is equivalent to call `engine.printMessage(symbol, exception)` and can therefore be replaced by such a corresponding call and removed.
Furthermore the methods
- `SwingFunctions.printArgMessage(IAST, int[], EvalEngine)`
- `SwingFunctions.printMessage(ISymbol, String, final IAST, EvalEngine)`
- `SwingFunctions.printMessage(ISymbol, Exception, EvalEngine)`
are never used within Symja and could therefore be removed. Or are they intended to be used by users?
=> [CleanUp-Logging] remove unused print methods and in-line duplicates

symja_android_library/matheclipse-external/pom.xml
Remove the log4j-api dependency of Symja's external module that is not required since JAS is included as Maven-Dependency and not embedded any more with commit 3788b02f561538110312d67cfbc761a2ed5f577e respectively PR #311 (which also contained this removal).
=> [External] Remove now unused log4j-api dependency

symja_android_library/pom.xml
This PR updates the org.apache.logging.log4j dependencies to version 2.15.0.
=> [POM] update to log4j 2.15.0

.github/dependabot.yml
This PR enables the automatic version update PR creation by dependabot for Symja.
Dependabot then checks for more recent versions of dependencies in Symja's pom.xml files on a daily basis. If an update for a dependency is found dependabot automatically creates PR to update that dependency. We can then review it and decide to merge or abandon that PR.
The same is done for GitHub action plug-ins.
This avoids the need to check for dependency updates manually and ensures we get informed about version updates within one day.
The documentation can be found here:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically
=> Enable dependabot version updates for Symja

symja_android_library/pom.xml
This PR specifies the versions of all plug-ins that were previously just inherited from the (implicitly specified) super-pom.
Because this pom changes with the Maven versions the stability of the build can be negatively influenced.
Specifying the versions of all used plug-ins improves stability of the Maven build.
Furthermore the minimal required Maven version of 3.2.0 is enforced now.
Available updates for build plug-ins can be checked with the following
command:
mvn versions:display-plugin-updates versions:display-property-updates
=> [Build] configure plug-ins inherited from super-pom and enforce Maven 3.2.0+

symja_android_library/eclipse/symja--jib-build.launch, symja_android_library/eclipse/symja--jib-dockerbuild.launch, symja_android_library/pom.xml
As we have discussed the `matheclipse-jar` module is just used to build Symja's docker container and not intended to be published.
This module can therefore should not participate in the default Symja build and can be removed from Symja's root pom.xml.
=> [Build] remove matheclipse-jar from build

symja_android_library/pom.xml
As we have discussed the `matheclipse-beakerx` module is stale and not intended to be published.
This module can therefore should not participate in the default Symja build and can be removed from Symja's root pom.xml.
Furthermore it relies on dependencies not available on Maven-Central which is discouraged for artefacts deployed there.
=> [Build] remove matheclipse-beakerx module from build

.github/workflows/maven.yml
This PR improves the current build workflow in the following ways
- set a timeout at 15min
to guard against long running builds (like in #349) that eat up a significant amount of Symja's free build minutes. At the moment the build runs about 4~5min, so for a regular build the timeout is more than sufficient. If the regular build time increases the timeout can be adjusted accordingly.
- use `temurin` instead of `adopt` java distribution.
Adopt is deprecated according to the [setup-java action doc](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#adopt).
- use build in maven cache of the `setup-java` action, which avoids the need to use the cache action (internally the `setup-java` action uses that action but it avoids configuration in the workflow) and can be even …
=> [Build] set 15min timeout, use 'temurin' java and use setup-java cache

.github/workflows/maven-build-master-and-publish-snapshot.yml, .github/workflows/maven-build-pr.yml, symja_android_library/pom.xml
This PR is the first preparatory step towards the Symja release deployment to Maven-Central and implements the continuos deployment of a snapshots build to the OSSRH snapshot-repository on each push to the master branch.
To implement the following changes are done
- Create publication profile
- move source-jar and java-doc creation there (speeds up PR builds)
- use nexus-staging-maven-plugin for deferred deployment of snapshots
- Create separate workflow to build and build snapshots of master-branch on each push.
The existing workflow is only used for PRs and is renamed accordingly.
- adapt server-ids in pom.xml to workflow and fix deployment data
=> [Build] Set up automatic publication of SNAPSHOT master builds (#193)

symja_android_library/pom.xml
This PR has the goal to guard against accidental releases (by pushing a release versions to the master branch) and adds the `banDuplicatePomDependencyVersions` enforcer rule.
If one really wants to perform a release the property `-Drelease.build=true` has to be set in the Maven build command to disable the introduced enforcer rule.
=> [Build] guard against accidental releases and add common enforcer rules

symja_android_library/matheclipse-beakerx/pom.xml, symja_android_library/matheclipse-jar/pom.xml, symja_android_library/pom.xml
With PR #348 and #355 I removed the `matheclipse-jar` and `matheclipse-beakerx` from the root pom's `modules` element with the intention to not publish those modules to Maven-Central.
Although this approach is perfectly valid in itself, it has two downsides:
1. The Eclipse-M2E importer does not consider those modules at the moment, so one has to explicitly import each excluded module one by one and cannot perform a bulk import.
2. Those projects are not build in Symja's regular build, so compile errors are not observed immediately and the code base might run out of sync over the time (this can be speed up if the projects are also not in the workspace).
Therefore those modules are added to the modules-section/Maven reactor again. To still suppress their deployment the corresponding …
=> [Build] disable deployment of 'internal' modules and not exclude them

symja_android_library/pom.xml, symja_android_library/tools/pom.xml
This PR (as part of #271) adds a `tools/pom.xml` to make the `tools` folder a full-fledged Maven project (the folder structure is already in Maven style). This way the `tools` project is imported in the workspace if one imports all Symja projects and is also build in the regular Symja build it is always kept in sync with the other modules and never forgotten in some refactoring or similar.
=> [Tools] Make 'tools'-folder a Maven project (#271)

readme.md
This PR adjusts the readme to reflect the renaming of module 'frontend' to 'parser' (I forgot that in the previous commit).
=> [ReadMe] reflect renaming of module 'frontend' to 'parser'

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ASTElementLimitExceeded.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/AbortException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ArgumentTypeException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ArgumentTypeStopException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/BigIntegerLimitExceeded.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/BreakException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ConditionException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ContinueException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/DialogReturnException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/FailedException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/FlowControlException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/IterationLimitExceeded.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/JASConversionException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/LimitException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/MemoryLimitExceeded.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/NoEvalException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/PolynomialDegreeLimitExceeded.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/RecursionLimitExceeded.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ResultException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ReturnException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/RuleCreationError.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/SymjaMathException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ThrowException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/TimeoutException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ValidateException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/VisitorRemoveLevelSpecification.java, symja_android_library/matheclipse-parser/src/main/java/org/matheclipse/parser/client/SyntaxError.java, symja_android_library/matheclipse-parser/src/main/java/org/matheclipse/parser/client/math/ArithmeticMathException.java, symja_android_library/matheclipse-parser/src/main/java/org/matheclipse/parser/client/math/MathException.java
This PR cleans up Symjas exceptions by:
- removing unused fields/getters/constructors
- removing implicitly created constructors or super-calls 
- restricting visibilities and modifiability as far as possible
- removing empty comments
- removing unnecessary calls of `toString()`
=> [Exceptions] clean up and remove unused/unnecessary elements

symja_android_library/matheclipse-parser/src/main/java/org/matheclipse/parser/client/ParserConfig.java, symja_android_library/matheclipse-parser/src/main/java/org/matheclipse/parser/client/SyntaxError.java
As we have discussed a while ago this enables capturing of the stack-trace for `SyntaxError` Exceptions all the time.
Syntax errors are not performance sensitive and their stack-trace is usually helpful to identify problems.
=> [SyntaxError] always fill stackTrace

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/EvalEngine.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/FlowControlException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/LimitException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/exception/ResultException.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/AbstractAST.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/VisitorRemoveLevelSpecification.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/core/fuzz/ExprEvaluatorTests.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/core/fuzz/TeXTests.java
As we have discussed a while ago, this PR changes the following `SymjaMathException` to be `FlowControlExceptions`:
- LimitException
- ResultException
- StopException
Affected Catch-clauses are simplified and the `serialVersionUID` of long standing classes are re-generated to reflect the change in the class-hierarchy.
=> Change Limit-, Result- and StopExceptions to be FlowControlExceptions

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/basic/Config.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/LowercaseTestCase.java
Having version literals in the code is bad because they have to be adjusted for each release. Furthermore it is problematic for the release process, because in that process the SNAPSHOT suffix of the version is removed. In order to run the tests successfully for release versions that literals would have to be adjusted in the release process too (IMHO this is discouraged).
This PR changes the tests to compare the result of the $version expression with the result of `Config.getVersion()`. I think it is not the intention to test the latter but the code that lead to it.
Furthermore I think the case for `resourceAsStream==null` does not need to be handled. At least when each Maven-project is imported individually into Eclipse M2E creates the read `pom.properties` on each workspace build.
@axkr …
=> [Core] Make version literals obsolete and use version of core not parser

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/basic/Config.java
In some circumstances in the IDE the pom.properties to be read is not
generated/available. To not break developers applications/tests a
default version is returned instead of throwing an exception.
=> [Config] return "0.0.0" if version read failed in getVersion()

symja_android_library/matheclipse-external/src/main/resources/com.baeldung/LICENSE, symja_android_library/matheclipse-external/src/main/resources/com.baeldung/projectInfo.txt, symja_android_library/matheclipse-external/src/main/resources/de.lab4inf.math/licence.txt, symja_android_library/matheclipse-external/src/main/resources/de.lab4inf.math/projectInfo.txt, symja_android_library/matheclipse-external/src/main/resources/jp.ac.kobe_u.cs.cream/FUNCTIONS, symja_android_library/matheclipse-external/src/main/resources/jp.ac.kobe_u.cs.cream/LICENSE, symja_android_library/matheclipse-external/src/main/resources/jp.ac.kobe_u.cs.cream/README, symja_android_library/matheclipse-external/src/main/resources/jp.ac.kobe_u.cs.cream/projectInfo.txt, symja_android_library/matheclipse-external/src/main/resources/tech.tablesaw/LICENSE.txt, symja_android_library/matheclipse-external/src/main/resources/tech.tablesaw/projectInfo.txt, symja_android_library/matheclipse-external/src/main/resources/uk.ac.ed.ph.snuggletex/licence.txt, symja_android_library/matheclipse-external/src/main/resources/uk.ac.ed.ph.snuggletex/projectInfo.txt, symja_android_library/matheclipse-gpl/src/main/resources/de.tilman_neumann.jml/LICENSE, symja_android_library/matheclipse-gpl/src/main/resources/de.tilman_neumann.jml/projectInfo.txt, symja_android_library/matheclipse-io/src/main/resources/tech.tablesaw/LICENSE.txt, symja_android_library/matheclipse-io/src/main/resources/tech.tablesaw/projectInfo.txt
This PR adds the legal files (licenses, NOTES if available, etc.) for sources of other projects that are embedded in the `matheclipse-core` and `matheclipse-io` module.
I searched for them with best effort and hope they are complete (since I'm not a lawyer I cannot grantee anything).
For each project of which sources are embedded I added a `projectInfo.txt` containing the URL to what I assume is the main project website. 
The projects are:
- com.baeldung
- de.lab4inf.math
- jp.ac.kobe_u.cs.cream
- tech.tablesaw
- uk.ac.ed.ph.snuggletex
=> [External] add legal files for embedded external source code

symja_android_library/pom.xml
This PR resolves #347.
As suspected since version 2.20 the `maven-surefire-plugin` additionally detects classes with names like `*Tests.java` as tests and runs them in its test goal.
Unfortunately those tests do not pass respectively hang.
On the long run we should fix and enable those tests. For now I just exclude them to be able to perform the update.
=> [Tests] Update to maven-surefire-plugin 3.0.0-M5 (#347)

symja_android_library/matheclipse-beakerx/src/main/java/com/twosigma/beakerx/symjamma/evaluator/SymjaMMAEvaluator.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/CompilerFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/OutputFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/MathMLUtilities.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/AbstractAST.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/AbstractIntegerSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BigFractionSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BigIntegerSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Blank.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BuiltInDummy.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ComplexNum.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ComplexSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/F.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/FractionSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/IntegerSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Num.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Pattern.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/PatternSequence.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/StringX.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Symbol.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/interfaces/IExpr.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/tensor/qty/QuantityImpl.java, symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/eval/Console.java, symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/eval/MMAConsole.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/JavaFormTestCase.java, symja_android_library/tools/src/main/java/org/matheclipse/core/preprocessor/ElementPreprocessor.java, symja_android_library/tools/src/main/java/org/matheclipse/core/preprocessor/ExprPreprocessor.java, symja_android_library/tools/src/main/java/org/matheclipse/core/preprocessor/RulePreprocessor.java
The variables argument of `IExpr.internalJavaString()` was `Function<IExpr, ? extends CharSequence> variables` but the function is only called with ISymbol objects. Therefore I suggest to make it more specific and change the function's input argument to be of type `ISymbol`:
`Function<ISymbol, ? extends CharSequence> variables`
Then functions passed to `internalJavaString()` don't have to check if the argument is an ISymbol or not.
Furthermore the constant `F.CNullFunction` is inlined. It's lambda is trivial and because it is a non capturing lambda the JVM reuses the same instance at one location for each call (if not for the entire class or JVM).
=> [Core] make internalJavaString() variables function more specific

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/AbstractFractionSym.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/FractionTestCase.java
This PR speeds up AbstractFractionSym.valueOfConvergent() by converting the Stream of converging BigFractions into an iterative algorithm that accepts a special predicate to test if the iteration has converged.
This avoids the creation of many unused `BigFraction` objects. In my simple benchmark this improved the runtime about 1/3.
Furthermore this prepares the internal re-use of the converging function with different parameters.
=> [Core] speed up rationalization

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Num.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/interfaces/INumber.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/interfaces/ISignedNumber.java
Overwriting `IExpr.evalDouble()` and `IExpr.evalComplex()` in `ISignedNumber` respectively overwriting `IExpr.evalComplex()` in `ISignedNumber` avoids the indirection that requires an `EvalEngine`. This change therefore should speed up the mentioned methods for instances of those interfaces.
=> [Core] overwrite evalDouble()/evalComplex() in number interfaces

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/AbstractIntegerSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/F.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/IntegerSym.java
This PR ensures that the constant for the integer value 1000 from `F` is used in `AbstractIntegerSym.valueOf()`. 1000 is a commonly used constant when it comes to conversion of SI Units and it is the only integer constant not covered by the integer-expression cache. Using the cached constant can reduce the number of created objects.
Furthermore the `CACHE` of `IntegerSym` is moved to `IntegerSym` because it can cause classloading issues if a sub-class is referenced during the initialization of the super class.
=> [Core] Use cached constant for int 1000 and move int-cache to IntegerSym

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/AbstractFractionSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BigFractionSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BigIntegerSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ComplexSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/NumberUtil.java
This PR improves/simplifies the overflow check of int/long values by using the `bitLength()` of a `BigInteger` instead of checking if BigInteger.toInt/Long() throws an exception. This allwows to use other methods which make the code IMHO more readable and likely yield to a better performance.
Furthermore a StringBuilder is replaced by String concatenation using + where it is not necessary.
=> [Core] improve overflow checks of int/long values

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BigFractionSym.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BigIntegerSym.java, symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/JavaFormTestCase.java
This PR fixes the java-code generation for BigIntegerSym objects whose numerator or denominator is too large to be represented by a long and improves the code generation for BigIntegerSym.
Before BigIntegerSym used the BigInteger-String constructor vor values that are larger than a int, but did not consider that a long could be sufficient.
=> [Core] fix java code generation for fractions too large for long

.github/workflows/maven-perform-release.yml, CHANGELOG.md, symja_android_library/pom.xml
This PR adds the automated release process (carried out with a dedicated GH-workflow) for the initial Symja release to Maven-Central.
To perform a release one only has to run the new workflow and the current SNAPSHOT version is converted to a release version and published to Maven-Central. A corresponding GH-release is created as well as a dedicated header in the changelog.
@axkr this also adds the CHAGELOG.md.
Please add the change-log items at the line marked with `TODO` (which can be removed).
=> [RelEng] Set up automatic release process

readme.md
This PR adds Badges to the readme.md for the latest Symja release available on Maven-Central (in the first row) as well as a badge for the master build state and the latest snapshot version in the OSSRH nexus repo.
Finally it looks like this:
=> [ReadMe] add Maven-Central badges and only use pure Markdown

.github/workflows/maven-perform-release.yml, CHANGELOG.md
This prepares the release process of Symja for subsequent releases by using [stefanzweifel/changelog-updater-action](https://github.com/stefanzweifel/changelog-updater-action) with the latest enhancements.
Furthermore it formats the changelog.md (which will also be done by the mentioned action during release).
Maybe there will be more improvements in the mentioned action that can be leveraged to simplify the creation of the link in the GH release to the changelog-entry, which is why this is a draft for now.
=> [RelEng] use changelog-updater-action to prepare for subsequent releases

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/HMArrayList.java
The method `Arrays.stream(T[] array, int startInclusive, int endExclusive)` takes the exclusive end-Index as last element, not the length of the stream. This PR adjusts the arguments accordingly.
=> Fix incorrect endIndex in HMArrayList.stream()

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/EvalEngine.java
- [yes ] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)
I suggest to rename `evalFlatOrderlessAttributesRecursive` as `evalFlatOrderlessAttrsRecursive` by replacing full term `Attributes` with its well-known abbreviations. In addition, `Attrs` is widely used in this project. Such abbreviations are common and well-known, and thus employing such well-known abbreviation would not result in confusion, but may improve the readability of the source code.
Accordingly, I have renamed the method by applying rename method refactoring, and submitted the pull request. No other changes are involved in the PR.
Would you please kindly review the PR. Thanks.
Did you add a unit test?
No
=> Rename method name

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/tex/TeXFormFactory.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/tex/TexFormSymbolOptions.java
Add `TexFormSymbolOptions.java` to allow to change tex output for different use cases.
What was changed?
For expression `Log(x)*Sin(x)==2`, with `TexFormSymbolOptions` we can customize the tex output:
- `Ln(x) * Sin(x) = 2`
- `Log(x) * Sin(x) == 2`
=> Add `TexFormSymbolOptions.java` to allow to change tex output for different use cases.

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/FileFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/GraphFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/UnitTestingFunctions.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/WL.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/data/InputStreamExpr.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/tex/TeXSegmentParser.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/Export.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/ExportString.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/sympy/core/Expr.java
Guava can be a dependency difficult to handle due to its many major versions. At the same time many of its great features have been migrated to the JDK and the Java standard library. If possible standard Java should be used if easily possible.
=> Replace Guava with standard Java where easily possible

.github/actions/setup-java-for-deployment/action.yml, .github/workflows/maven-build-master-and-publish-snapshot.yml, .github/workflows/maven-build-pr.yml, symja_android_library/matheclipse-external/pom.xml, symja_android_library/pom.xml
The former uses the latter under the hood, thus the latter is always more recent and more powerful.
=> [Build|OSGi] Migrate from Maven-Bundle-Plugin to Bnd-Maven-Plugin

.github/workflows/codeql.yml
The Java setup and build configuration is the same as for the maven-build-pr workflow except that the test execution is skipped.
=> [Build] Adapt CodeQL workflow to toolchain and Java-17 build setup

symja_android_library/pom.xml
This avoids re-releases of Symja for each new major version of Guava and in general relaxes the version restrictions for Symja regarding Guava in OSGi runtimes.
Requires https://github.com/axkr/symja_android_library/pull/893
=> [OSGi] Import Guava packages without upper bound

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/F.java
The 'base' and 'z' arguments of 'F.Log(z, base)' are actually swapped and the method signatures must be 'F.Log(z, base)'. The documentation and trying it out verifies that.
=> Fix parameter names of two argument F.Log function

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/basic/Config.java, symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/RootsFunctions.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/system/ExprEvaluatorTestCase.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/system/SolveTest.java
Dear @axkr ,
I added an option `Config#MAX_POLYNOMIAL_DEGREE_LAGUERRE_SOLVER` to limit the maximum degree of a polynomial before passing to `LaguerreSolver`
SolveTest#testSolveBigExponent
```java
@Test
public void testSolveBigExponent() {
// message: Exponent ist out of bounds for function Factor.
check("Solve(40==5000000/E^(x/(2*1/10^6)),x)", //
"{{x->ConditionalExpression(I*1/250000*Pi*C(1)+Log(125000)/500000,C(1)∈Integers)}}");
}
```
=> Added Config#MAX_POLYNOMIAL_DEGREE_LAGUERRE_SOLVER option

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/VisitorLevelSpecification.java
Check recursion limit in `VisitorLevelSpecification` instead of relying on Java's StackOverflowError.
The current implementation may not work, JVM may kill the process when StackOverflowError occurs.
```java
interface IAST {
default IExpr acceptChecked(IVisitor visitor) {
try {
return accept(visitor);
} catch (StackOverflowError soe) {
RecursionLimitExceeded.throwIt(Integer.MAX_VALUE, this);
}
return F.NIL;
}
}
```
=> Check recursion limit in `VisitorLevelSpecification`

symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/NumberTheory.java, symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/system/LowercaseTestCase.java
Throw BigIntegerLimitExceeded instead of IterationLimitExceeded in NumberTheory#fibonacci
=> Throw BigIntegerLimitExceeded instead of IterationLimitExceeded in NumberTheory#fibonacci
