axkr/symja_android_library

- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/AlgebraicFunctions.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/Exponentials.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/HyperbolicFunctions.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/IndependentTestSuites.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/InverseHyperbolicFunctions.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/InverseTrigFunctions.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/Logarithms.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/SpecialFunctions.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/rubi/TrigFunctions.java
> Some more linebreaks for eklypse

- readme.md
> AppStore badge

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/PredicateQ.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/system/LowercaseTestCase.java
---
Added Gaussian integer option to OddQ.
Added test cases to lowercaseTestCase.
If Imaginary and real parts are odd then it makes false.
If either one is odd, it's true.
If there is only one real or imaginary part, only one is considered.
X
Since EvenQ is added last time, I added OddQ.
Let me know if there is anything that needs to be corrected.
> Gaussian Integer for OddQ

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/Arithmetic.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ComplexSym.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/expression/ComplexSymTest.java
- [+] This pull request isn't a duplicate of an [existing one][1]
- [+] Commit messages are detailed 
- [+] Documentation has been updated to reflect changes
- [+] Tests have been added / updated to reflect changes
---
Adds test cases for ComplexSym.
Adds new method ComplexSym.integerPartDivisionGaussian
Finds integer part of division of two complex numbers "Gaussian Numbers Division"
No
-
> division of two complex numbers "euclidean division for complex numbers, Gaussian Numbers"

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ComplexSym.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/expression/ComplexSymTest.java
- [+] This pull request isn't a duplicate of an [existing one][1]
- [+] Commit messages are detailed 
- [+] Documentation has been updated to reflect changes
- [+] Tests have been added / updated to reflect changes
---
Improved GCD function for special cases
Find GCD
no
no
> Improved GCD function for special cases

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/output/OutputFormFactory.java
Bug fixes #267 missing operator when converting complex number to string.
> Fix missing operator when converting complex number to string.

- symja_android_library/matheclipse-api/src/main/java/org/matheclipse/api/Pods.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/FileFunctions.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/MathUtils.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/interfaces/AbstractFunctionEvaluator.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/F.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/WL.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/Documentation.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/Export.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/ExportString.java
- symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/servlet/AJAXDocServlet.java
- symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/servlet/AJAXQueryServlet.java
- symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/servlet/AJAXSearchServlet.java
- symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/servlet/MMAAJAXQueryServlet.java
Using try-with-resources usually requires less code and it is close to bullet-proof that the resources is really closed.
> [CleanUp] use try-with-resource

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/IOFunctions.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/EvalEngine.java
- symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/servlet/ServletServer.java
- symja_android_library/matheclipse-logging/src/main/resources/log4j2.properties
As discussed in our call:
- Revert "Revert some output settings for error messages in console and servlet apps."
- fix logger calls in `IOFunctions` and add comments to log-config
> Clean up logging

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/GraphicsFunctions.java
Point is still black by default.
> Set default color of all 3D primitives but Point to white

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/GraphicsFunctions.java
There was just 1 white ambient light in the scene, now there's 1 ambient
light (not white) and 3 directional lights.
> Improve Graphics3D default lighting

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/ListPlot3D.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/ListPointPlot3D.java
Use mathics-threejs-backend in ListPointPlot3D and ListPlot3D.
Please feel free to do changes.
> mathics-threejs-backend ListPointPlot3D and ListPlot3D

- symja_android_library/matheclipse-api/pom.xml
- symja_android_library/matheclipse-beakerx/pom.xml
- symja_android_library/matheclipse-core/pom.xml
- symja_android_library/matheclipse-discord/pom.xml
- symja_android_library/matheclipse-external/pom.xml
- symja_android_library/matheclipse-frontend/pom.xml
- symja_android_library/matheclipse-gpl/pom.xml
- symja_android_library/matheclipse-io/pom.xml
- symja_android_library/matheclipse-jar/pom.xml
- symja_android_library/matheclipse-logging/pom.xml
- symja_android_library/pom.xml
This PR re-formats the headers of all pom.xml files and remove unnecessary release profile from child-modules, everything necessary will be specified in the root pom.xml or is not relevant for releases.
> [Build] clean up and format pom.xml files

- .github/workflows/maven-build-master-and-publish-snapshot.yml
- .github/workflows/maven-build-pr.yml
- .github/workflows/maven.yml
- symja_android_library/pom.xml
Test publish snapshot workflow only with gpg signing
> Test publish snapshot workflow only with gpg signing

- .github/workflows/maven-build-master-and-publish-snapshot.yml
- symja_android_library/pom.xml
> [TestPublishing] enable test deployment

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/Programming.java
Remove redundant or unused code-paths in Programming
> [CleanUp] remove redundant or unused code-paths in Programming

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/WL.java
- symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/LowercaseTestCase.java
- symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/test/ImportTest.java
Clean up: Use class literal and try-with-resource
> [CleanUp] use class literal and try-with-resource

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/EvalEngine.java
- symja_android_library/matheclipse-gpl/src/main/java/org/matheclipse/gpl/numbertheory/BigIntegerPrimality.java
CleanUp: use `ThreadLocal.withInitial()`
> [CleanUp] use ThreadLocal.withInitial()

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/ListLinePlot3D.java
Normalize coordinates of ListLinePlot3D so Symja behavior is closer to Wolfram Language.
> Normalize coordinates of ListLinePlot3D

- symja_android_library/matheclipse-parser/src/test/java/org/matheclipse/parser/test/BracketBalancerTestCase.java
- symja_android_library/matheclipse-parser/src/test/java/org/matheclipse/parser/test/ParserTestCase.java
- symja_android_library/matheclipse-parser/src/test/java/org/matheclipse/parser/test/RelaxedParserTestCase.java
This PR is part of #239 and ports the test of module `matheclipse-parser` to JUnit-5 and simplifies them.
> [Parser] port tests to Junit-5 and simplify them (#239)

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/ListLinePlot3D.java
ListLinePlot3D had a wrong scale when you draw multiple lines using coordinates, this PR is an attempt to fix that.
> Fix wrong scale with multiple lines in ListLinePlot3D

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/ListFunctions.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/AbstractVisitor.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/IVisitor.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/VisitorExpr.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/VisitorLevelSpecification.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/VisitorReplaceAll.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/VisitorReplaceAllLambda.java
Format and clean up visitors and fix Sonar-Lint complaints.
> [Visitors] format and clean up visitors

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/visit/VisitorReplaceAll.java
> [ReplaceVisitor] fix SonarLint complaints

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/ClusteringFunctions.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BuiltInDummy.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BuiltInRubi.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/PatternNested.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Symbol.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/data/InterpolatingFunctionExpr.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/data/NumericArrayExpr.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/patternmatching/PatternMatcher.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/reflection/system/Solve.java
- symja_android_library/matheclipse-io/src/main/java/org/matheclipse/core/tensor/io/ext/WavefrontImpl.java
- symja_android_library/matheclipse-io/src/main/java/org/matheclipse/core/tensor/io/ext/WavefrontObjectImpl.java
- symja_android_library/matheclipse-io/src/main/java/org/matheclipse/io/builtin/SwingFunctions.java
Apply Eclipse Clean-Up `Add serial version ID` to the entire codebase (except external code).
> [CleanUp] Apply Eclipse clean-up "Add serial version ID"

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/CompilerFunctions.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/LinearAlgebra.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/util/Assumptions.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Context.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ContextPath.java
- symja_android_library/matheclipse-parser/src/main/java/org/matheclipse/parser/client/ast/FunctionNode.java
> [CleanUp] fix warnings

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/NumberTheory.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/AbstractFractionSym.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/BigFractionSym.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/FractionSym.java
This PR cleans up and simplifies the rationalization of floating point numbers.
> Clean-up rationalization of floats

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/AbstractFractionSym.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/F.java
This PR further unifies the code of `AbstractFractionSym` and the fraction methods in class `F`.
Some methods were re-ordered to improve their grouping.
> [CleanUp] Unify rationalization of floats

- symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/AbstractTestCase.java
- symja_android_library/matheclipse-io/src/test/java/org/matheclipse/io/system/FractionTestCase.java
> [Tests] clean up and port FractionTestCase to JUnit5 (#239)

- .github/actions/setup-java-for-deployment/action.yml
- .github/workflows/maven-build-master-and-publish-snapshot.yml
- .github/workflows/maven-build-pr.yml
This PR introduces a reusable composite action that contains the java setup referenced by all GH workflows of Symja. This reduces the configuration effort and avoids inconsistent setups.
> [Build] unify java setup into reusable composite action

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/eval/EvalEngine.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Context.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ContextPath.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/F.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Symbol.java
This PR applies some minor simplifications and clean-ups to Context(-Path), EvalEngine, Symbol and F.
> Simplify and clean-up Context(-Path), EvalEngine, Symbol and F

- symja_android_library/matheclipse-discord/pom.xml
- symja_android_library/matheclipse-jar/pom.xml
Update version of discord and jar module to `2.1.0-SNAPSHOT` to match the other modules.
> [RelEng] update parent version for discord and jar module

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/basic/Config.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/ExpTrigsFunctions.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ApcomplexNum.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ApfloatNum.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/ComplexNum.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/expression/Num.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/config/SystemConfigurationTest.java
- symja_android_library/matheclipse-core/src/test/java/org/matheclipse/core/system/ExprEvaluatorTestCase.java
Introduce a new field `ROUND_MODE` in `Config` class.
This allow to control the rounding mode used in number classes such as `Num, ApfloatNum, ComplexNum`
```
SystemConfigurationTest#testRoundingMode
```
> Allow to control rounding mode used in Symja

- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/basic/Config.java
- symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/output/OutputFormFactory.java
Add an option to control the default value of `OutputFormFactory#fIgnoreNewLine`
This option allow to control the default value of OutputFormFactory#fIgnoreNewLine, which obtains from OutputFormFactory#get* methods
> Add an option to control the default value of `OutputFormFactory#fIgnoreNewLine`

- .github/workflows/maven-build-master-and-publish-snapshot.yml
Enable gpg-signing for snapshots builds again. This is also necessary for new releases.
> [Build] Enabled gpg-signing for snapshots builds again

- symja_android_library/doc/functions/SeriesCoefficient.md
- symja_android_library/matheclipse-core/src/main/resources/doc/functions/SeriesCoefficient.md
Small PR - Commit 3ec109ffbef7035ddb96cf773fd03e3be7b36e52 moved the `SeriesCoefficientRules.m` file. This PR adjusts sources to changes.
> Update `SeriesCoefficientRules.m` reference
